---
include:
  - board: nice_nano
    shield: sweeple_left
    snippet: zmk-usb-logging
  - board: nice_nano
    shield: sweeple_right
    snippet: zmk-usb-logging
  - board: nice_nano
    shield: sweeple_trackpoint
    snippet: zmk-usb-logging
  - board: nice_nano
    shield: settings_reset
